
/* Autogenerated file, do not edit! */

/* eslint-disable */
import { AztecAddress, CompleteAddress } from '@aztec/aztec.js/addresses';
import { type AbiType, type AztecAddressLike, type ContractArtifact, EventSelector, decodeFromAbi, type EthAddressLike, type FieldLike, type FunctionSelectorLike, loadContractArtifact, loadContractArtifactForPublic, type NoirCompiledContract, type U128Like, type WrappedFieldLike } from '@aztec/aztec.js/abi';
import { Contract, ContractBase, ContractFunctionInteraction, type ContractInstanceWithAddress, type ContractMethod, type ContractStorageLayout, DeployMethod } from '@aztec/aztec.js/contracts';
import { EthAddress } from '@aztec/aztec.js/addresses';
import { Fr, Point } from '@aztec/aztec.js/fields';
import { type PublicKey, PublicKeys } from '@aztec/aztec.js/keys';
import type { Wallet } from '@aztec/aztec.js/wallet';
import MessageBridgeContractArtifactJson from './MessageBridge.json' with { type: 'json' };
export const MessageBridgeContractArtifact = loadContractArtifact(MessageBridgeContractArtifactJson as NoirCompiledContract);



/**
 * Type-safe interface for contract MessageBridge;
 */
export class MessageBridgeContract extends ContractBase {
  
  private constructor(
    instance: ContractInstanceWithAddress,
    wallet: Wallet,
  ) {
    super(instance, MessageBridgeContractArtifact, wallet);
  }
  

  
  /**
   * Creates a contract instance.
   * @param address - The deployed contract's address.
   * @param wallet - The wallet to use when interacting with the contract.
   * @returns A promise that resolves to a new Contract instance.
   */
  public static async at(
    address: AztecAddress,
    wallet: Wallet,
  ) {
    return Contract.at(address, MessageBridgeContract.artifact, wallet) as Promise<MessageBridgeContract>;
  }

  
  /**
   * Creates a tx to deploy a new instance of this contract.
   */
  public static deploy(wallet: Wallet, wormhole_address: AztecAddressLike, chain_id: (bigint | number), owner: AztecAddressLike, message_fee: (bigint | number)) {
    return new DeployMethod<MessageBridgeContract>(PublicKeys.default(), wallet, MessageBridgeContractArtifact, MessageBridgeContract.at, Array.from(arguments).slice(1));
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified public keys hash to derive the address.
   */
  public static deployWithPublicKeys(publicKeys: PublicKeys, wallet: Wallet, wormhole_address: AztecAddressLike, chain_id: (bigint | number), owner: AztecAddressLike, message_fee: (bigint | number)) {
    return new DeployMethod<MessageBridgeContract>(publicKeys, wallet, MessageBridgeContractArtifact, MessageBridgeContract.at, Array.from(arguments).slice(2));
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified constructor method.
   */
  public static deployWithOpts<M extends keyof MessageBridgeContract['methods']>(
    opts: { publicKeys?: PublicKeys; method?: M; wallet: Wallet },
    ...args: Parameters<MessageBridgeContract['methods'][M]>
  ) {
    return new DeployMethod<MessageBridgeContract>(
      opts.publicKeys ?? PublicKeys.default(),
      opts.wallet,
      MessageBridgeContractArtifact,
      MessageBridgeContract.at,
      Array.from(arguments).slice(1),
      opts.method ?? 'constructor',
    );
  }
  

  
  /**
   * Returns this contract's artifact.
   */
  public static get artifact(): ContractArtifact {
    return MessageBridgeContractArtifact;
  }

  /**
   * Returns this contract's artifact with public bytecode.
   */
  public static get artifactForPublic(): ContractArtifact {
    return loadContractArtifactForPublic(MessageBridgeContractArtifactJson as NoirCompiledContract);
  }
  

  public static get storage(): ContractStorageLayout<'config' | 'owner' | 'registered_emitters' | 'current_value'> {
      return {
        config: {
      slot: new Fr(1n),
    },
owner: {
      slot: new Fr(5n),
    },
registered_emitters: {
      slot: new Fr(6n),
    },
current_value: {
      slot: new Fr(7n),
    }
      } as ContractStorageLayout<'config' | 'owner' | 'registered_emitters' | 'current_value'>;
    }
    

  /** Type-safe wrappers for the public methods exposed by the contract. */
  public declare methods: {
    
    /** constructor(wormhole_address: struct, chain_id: integer, owner: struct, message_fee: integer) */
    constructor: ((wormhole_address: AztecAddressLike, chain_id: (bigint | number), owner: AztecAddressLike, message_fee: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_config() */
    get_config: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_current_value() */
    get_current_value: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_owner() */
    get_owner: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** is_emitter_registered(chain_id: integer, emitter_address: array) */
    is_emitter_registered: ((chain_id: (bigint | number), emitter_address: (bigint | number)[]) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** process_message(message_ciphertext: struct, message_context: struct) */
    process_message: ((message_ciphertext: FieldLike[], message_context: { tx_hash: FieldLike, unique_note_hashes_in_tx: FieldLike[], first_nullifier_in_tx: FieldLike, recipient: AztecAddressLike }) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** public_dispatch(selector: field) */
    public_dispatch: ((selector: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** receive_value(vaa: array, length: integer) */
    receive_value: ((vaa: (bigint | number)[], length: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** register_emitter(source_chain_id: integer, emitter_address: array) */
    register_emitter: ((source_chain_id: (bigint | number), emitter_address: (bigint | number)[]) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** send_value_private(destination_chain_id: integer, value: integer, fee_nonce: field) */
    send_value_private: ((destination_chain_id: (bigint | number), value: (bigint | number), fee_nonce: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** send_value_public(destination_chain_id: integer, value: integer, fee_nonce: field) */
    send_value_public: ((destination_chain_id: (bigint | number), value: (bigint | number), fee_nonce: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** sync_private_state() */
    sync_private_state: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;
  };

  
}
